### ISSUE TITLE
4.0.0.0 release possible?

### ISSUE THREAD

**Issue by rvanderwerf** [cazacugmihai/grails-pretty-time#13]
Hi for speed of looking up snapshots is it possible to make a release of the 4.0.0.0-SNAPSHOT to 4.0.0 release? We're using it on grails 3 and thus far seems ok.

**Comment by cazacugmihai** [comment]
Hi Ryan!

Can you create a pull request for this?

I also saw that some dependencies can be upgraded to the latest version:
* prettytime: 3.2.7.Final
* jodatime: 2.9.1

Thanks,
Mihai

**Comment by rvanderwerf** [comment]
PR sent!

**Comment by rvanderwerf** [comment]
Hi is this published on bintray somewhere?

**Comment by cazacugmihai** [comment]
https://bintray.com/cazacugmihai/plugins/grails-pretty-time

**Comment by cazacugmihai** [comment]
@rvanderwerf: Thank you for your help! :)

**Comment by cazacugmihai** [comment]
@rvanderwerf: Can we close the issue now?
